on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

include:
  - board: nice_nano
    shield: corne_left
  - board: nice_nano
    shield: corne_right
  - board: nice_nano_v2
    shield: lily58_left
  - board: nice_nano_v2
    shield: lily58_right
